[pytest]

addopts = [
    "-s"
]

pythonpath = [
    ".",
    "./scripts/",
    "./tests/"
]

testpaths = [
    "./scripts/"
]

python_files = [
    "pytest_runner.py"
]

markers = [
    "input_column_counter: Counts the input address counter",
    "output_column_counter: Counts the output address counter",
    "address_logic: Checks the address flip floping logic",
    "xilinx_tdpram_wrapper: Simulated the xpm wrapper",
    "axis_corner_turn_matrix: Simulation of the finaly project"
]